# Generated by Django 4.1.2 on 2022-10-09 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Dashboard', '0003_alter_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='a',
        ),
    ]
