# Generated by Django 4.1.2 on 2022-10-09 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Dashboard', '0005_rename_task_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='StartDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
